import apsw as sql
con = sql.Connection("mi_db.sqlite")

con.execute('''
    CREATE TABLE IF NOT EXISTS PROVEEDOR(
        ID INT PRIMARY KEY NOT NULL, 
        NOMBRE TEXT NOT NULL
    );
''')

con.execute('''
    CREATE TABLE IF NOT EXISTS COMPONENTE(
        ID INT PRIMARY KEY NOT NULL, 
        NOMBRE TEXT NOT NULL,
        DESCRIPCION TEXT,
        CANTIDAD INT
    );
''')

con.execute('''
    CREATE TABLE IF NOT EXISTS PRODUCTO(
        ID INT PRIMARY KEY NOT NULL, 
        NOMBRE TEXT NOT NULL,
        DESCRIPCION TEXT,
        CANTIDAD INT
    );
''')

con.execute('''
    CREATE TABLE IF NOT EXISTS proveedor_suministra_componente(
        ID_PROVEEDOR INT NOT NULL, 
        ID_COMPONENTE INT NOT NULL,
        PRIMARY KEY (ID_PROVEEDOR, ID_COMPONENTE),
        FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID),
        FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE(ID)
    );
''')

con.execute('''
    CREATE TABLE IF NOT EXISTS producto_compone_componente(
        ID_PRODUCTOS INT NOT NULL, 
        ID_COMPONENTE INT NOT NULL,
        PRIMARY KEY (ID_PRODUCTOS, ID_COMPONENTE),
        FOREIGN KEY (ID_PRODUCTOS) REFERENCES PRODUCTO(ID),
        FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE(ID)
    );
''')

# AHORA SUPONEMOS
# UN COMPONENTE SE COMPONE DE PIEZAS
# CADA PIEZA PERTENECE A UN SOLO COMPONENTE

con.execute('''
    CREATE TABLE IF NOT EXISTS PIEZA(
        ID INT NOT NULL, 
        STOCK INT,
        DESCRIPCION TEXT,
        ID_COMPONENTE INT,
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE(ID)
    );
''')

con.execute('''
    CREATE TABLE IF NOT EXISTS CONVENIO(
        ID INT NOT NULL,
        DESCRIPCION TEXT,
        ID_PROVEEDOR INT,
        PRIMARY KEY (ID),
        FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID) ON DELETE CASCADE
    );
''')

con.close()